name: mdb_fe
type: gradio-space
sdk: streamlit

metadata:
  space_id: Chris4K/mdb_fe
  original_url: https://huggingface.co/spaces/Chris4K/mdb_fe

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 13:26:18
